### ISSUE TITLE
Can't import DICOMDIR File

### ISSUE THREAD

**Issue by JossKenyon** [OmooLab/BioxelNodes#47]
Hello,

When I try to import the DICOMDIR File into Blender with the addon, I get this error.

I'm able to import the .dcm Male Head, but not this DICOMDIR file that the dentist gave me.

is this file compatible?
![Screenshot 2024-10-09 110222](https://github.com/user-attachments/assets/86e519ea-911f-4f2b-ba36-7b03e172eca8)

> Python: Traceback (most recent call last):
>   File "C:\Users\Joss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\bioxelnodes\operators\io.py", line 69, in execute
>     bpy.ops.bioxelnodes.parse_volumetric_data('INVOKE_DEFAULT',
>   File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 107, in __call__
>     ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Error: Get no vaild series.

**Comment by icrdr** [comment]
This is may caused by Simple ITK, It can't read DICOMDIR correctly. Simple ITK can read many formats, but it has a lot of problems reading DICOM files. I've collected tons of issues related to this matter.

I am already thinking that using pydicom instead.  It's in my plan, maybe v1.1.x

**Comment by JossKenyon** [comment]
Ah man unfortunate to hear that. So this type of file isn't compatible right now, but it will be in the future?

**Comment by icrdr** [comment]
I will let you know when v1.1.0 is released
